### ISSUE TITLE
The content is not displaying on the right way 

### ISSUE THREAD

**Issue by Kinfe123** [sdorra/content-collections#193] opened 2024-07-10 07:25 UTC
this for displaying the markdownx
` <MDXContent code={post.body} />
`
this for contentcollection config - 
```js
const posts = defineCollection({
  name: "Blogs",
  directory: "content/blogs",
  include: "*.mdx",
  schema: (z) => ({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    published: z.boolean(),
    image: z.string(),
    authors: z.array(z.string())
  }),
  transform: async (document, context) => {
    const body = await compileMDX(context, document);
    return {
      ...document,
      body,
    };
  },
});
```

i also have used it in combination with rehype and remark plugin from fumadocs-core but the contnt is being displayed like the image below. is there any mistake i made here ?
![image](https://github.com/sdorra/content-collections/assets/65047246/93b6ad81-8ff4-46b7-b6f3-17fc536a4295)

**Comment by Kinfe123** [comment] 2024-07-11 06:57
yeah it is imported from the right packate and i crossed checked that , i also even checked the generated file and it body do have js in it but when passing to the MdxContent component that u export from react fm it is displaying like the abov one

**Comment by Kinfe123** [comment] 2024-07-11 07:07
or let me try it with html transformer if that works out generating html.

**Comment by sdorra** [comment] 2024-07-11 13:13
@Kinfe123 is the repository public? Or can you give me access to it? I would like to take a look at the problem myself.

**Comment by AbePlays** [comment] 2024-07-13 11:52
@Kinfe123 FWIW I have this content-collections config that works for me.

```ts
import { defineCollection, defineConfig } from '@content-collections/core'
import { compileMDX } from '@content-collections/mdx'
import rehypePrettyCode from 'rehype-pretty-code'

export const posts = defineCollection({
  name: 'posts',
  directory: 'content/writing',
  include: '*.mdx',
  schema: (z) => ({
    title: z.string(),
    description: z.string(),
    publishedAt: z.string(),
  }),
  transform: async (document, context) => {
    const mdx = await compileMDX(context, document, {
      rehypePlugins: [[rehypePrettyCode, { theme: 'github-dark-dimmed' }]],
    })
    return { ...document, mdx }
  },
})

export default defineConfig({
  collections: [posts],
})
```

**Comment by sdorra** [comment] 2024-07-13 12:09
@Kinfe123 the code you have posted looks correct, but it is possible that you've documentation issue #198

Can you double check that you use `body` and not `content`, because if you use the content instead the result looks exactly as in your screenshot.

**Comment by Kinfe123** [comment] 2024-07-13 14:57
Now it is working by injecting html transformed file to in the Jsx as dangerouslySetInnerHTML

**Comment by sdorra** [comment] 2024-07-13 19:40
I'm closing this issue for now, but it should also work with compileMDX. If you can provide me access to a repository where I can reproduce the issue, please reopen the issue, and I'll take a look.

**Closed by sdorra** 2024-07-13 19:40 UTC
Labels: bug
